[toolchain]
anchor_version = "0.29.0"    # `anchor-cli` version to use(requires `avm`)
solana_version = "1.18.1"    # Solana version to use(applies to all Solana tools)

[features]
seeds = false
skip-lint = false

[programs.localnet]
valet_protocol = "C91FUDN641gSj567rWgcrnYc7mUSuWPs443irPYLoFPe"
demo_program = "H9nFQRTmB6t1xNrRnMAnrCtdRuMYFFYxFPvNTGRgP6Am"

[programs.devnet]
valet_protocol = "Ez6kSdsqyLLTKGa9rcUBtfUshmvPWgKtNsQTiXkGFk5s"
demo_program = "H9nFQRTmB6t1xNrRnMAnrCtdRuMYFFYxFPvNTGRgP6Am"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/thewuh/.config/solana/payround_deployer.json"

[scripts]
test = "ts-mocha -p ./protocol/tsconfig.json -t 1000000 protocol/ts/tests/**/*.test.ts"

[workspace]
members= [
  "protocol/programs/valet-protocol",
  "protocol/programs/demo-program"
]
types="protocol/ts/src/idl"
